import csv
import io
from datetime import datetime, date
from celery import shared_task
from .. import db


@shared_task(bind=True)
def send_daily_reminders(self):
    """
    Runs daily. Notifies trekkers whose trek starts within the next 3 days.
    Assignment requirement: daily reminder job.
    """
    from ..models import Booking, Trek, User

    today = date.today()
    upcoming = Trek.query.filter(
        Trek.status == "Open",
        Trek.start_date >= today,
    ).all()

    sent = 0
    for trek in upcoming:
        days_left = (trek.start_date - today).days
        if days_left not in [1, 2, 3]:
            continue

        bookings = Booking.query.filter_by(trek_id=trek.id, status="Booked").all()
        for booking in bookings:
            user = User.query.get(booking.user_id)
            if user:
                _send_email(
                    to=user.email,
                    subject=f"Jatayu | Your trek '{trek.name}' starts in {days_left} day(s)!",
                    body=f"""
Namaste {user.full_name}!

Your trek '{trek.name}' begins on {trek.start_date.strftime('%B %d, %Y')}.
Location: {trek.location}
Duration: {trek.duration_days} days

Pack well, trek safe. The mountains are waiting.

— Team Jatayu 🏔
                    """.strip()
                )
                sent += 1

    return {"status": "done", "reminders_sent": sent}


@shared_task(bind=True)
def send_monthly_admin_report(self):
    """
    Runs on the 1st of every month.
    Sends HTML report to admin with trek stats, booking counts, popular treks.
    Assignment requirement: monthly report job.
    """
    from ..models import Trek, Booking, User

    total_treks = Trek.query.count()
    total_bookings = Booking.query.count()
    total_users = User.query.filter_by(role="trekker").count()
    completed = Booking.query.filter_by(status="Completed").count()

    popular = db.session.execute(
        db.text("""
            SELECT t.name, COUNT(b.id) as count
            FROM treks t
            JOIN bookings b ON t.id = b.trek_id
            GROUP BY t.id, t.name
            ORDER BY count DESC
            LIMIT 5
        """)
    ).fetchall()

    popular_html = "".join(
        f"<tr><td>{r[0]}</td><td>{r[1]}</td></tr>" for r in popular
    )

    html = f"""
    <html><body style="font-family:sans-serif;color:#1a1a1a">
    <h2 style="color:#0f2818">Jatayu — Monthly Report ({datetime.now().strftime('%B %Y')})</h2>
    <table border="0" cellpadding="8">
      <tr><td>Total Treks</td><td><b>{total_treks}</b></td></tr>
      <tr><td>Total Users</td><td><b>{total_users}</b></td></tr>
      <tr><td>Total Bookings</td><td><b>{total_bookings}</b></td></tr>
      <tr><td>Completed Bookings</td><td><b>{completed}</b></td></tr>
    </table>
    <h3>Most Popular Treks</h3>
    <table border="1" cellpadding="8" style="border-collapse:collapse">
      <tr><th>Trek</th><th>Bookings</th></tr>
      {popular_html}
    </table>
    <p style="color:#666;font-size:12px">Generated by Jatayu on {datetime.now().strftime('%d %B %Y')}</p>
    </body></html>
    """

    _send_email(
        to="admin@jatayu.in",
        subject=f"Jatayu Monthly Report — {datetime.now().strftime('%B %Y')}",
        body=html,
        is_html=True,
    )

    return {"status": "done", "month": datetime.now().strftime("%B %Y")}


@shared_task(bind=True)
def export_booking_history(self, user_id):
    """
    User-triggered async CSV export.
    Assignment requirement: user-triggered background job with notification.
    """
    from ..models import Booking, User

    user = User.query.get(user_id)
    if not user:
        return {"error": "User not found"}

    bookings = Booking.query.filter_by(user_id=user_id).all()

    output = io.StringIO()
    writer = csv.writer(output)
    writer.writerow([
        "Booking ID", "Trek Name", "Location",
        "Start Date", "End Date", "Booking Date",
        "Status", "Amount Paid", "Payment Method"
    ])

    for b in bookings:
        trek = b.trek
        writer.writerow([
            b.id,
            trek.name if trek else "N/A",
            trek.location if trek else "N/A",
            trek.start_date.isoformat() if trek and trek.start_date else "N/A",
            trek.end_date.isoformat() if trek and trek.end_date else "N/A",
            b.booking_date.strftime("%Y-%m-%d") if b.booking_date else "N/A",
            b.status,
            f"₹{b.amount_paid}" if b.amount_paid else "N/A",
            b.payment_method or "N/A",
        ])

    csv_content = output.getvalue()

    # Save to file
    import os
    export_dir = "exports"
    os.makedirs(export_dir, exist_ok=True)
    filename = f"{export_dir}/booking_history_{user_id}_{datetime.now().strftime('%Y%m%d%H%M%S')}.csv"
    with open(filename, "w") as f:
        f.write(csv_content)

    # Notify user
    _send_email(
        to=user.email,
        subject="Jatayu | Your booking history export is ready",
        body=f"Namaste {user.full_name}! Your trek booking history CSV export is ready. Download it from your dashboard."
    )

    return {"status": "done", "user_id": user_id, "file": filename}


def _send_email(to, subject, body, is_html=False):
    """Helper — uses Flask-Mail when configured, logs to console in dev."""
    try:
        from flask import current_app
        from flask_mail import Mail, Message
        mail = Mail(current_app)
        msg = Message(subject=subject, recipients=[to])
        if is_html:
            msg.html = body
        else:
            msg.body = body
        mail.send(msg)
    except Exception as e:
        print(f"[EMAIL] To: {to} | Subject: {subject}")
        print(f"[EMAIL] Body preview: {str(body)[:120]}")
        print(f"[EMAIL] Error (dev mode, no mail server): {e}")


def send_daily_reminders_non_celery():
    """Non-Celery daily reminders."""
    from ..models import Booking, Trek, User
    today = date.today()
    upcoming = Trek.query.filter(
        Trek.status == "Open",
        Trek.start_date >= today,
    ).all()

    sent = 0
    for trek in upcoming:
        days_left = (trek.start_date - today).days
        if days_left not in [1, 2, 3]:
            continue

        bookings = Booking.query.filter_by(trek_id=trek.id, status="Booked").all()
        for booking in bookings:
            user = User.query.get(booking.user_id)
            if user:
                print(f"[GOOGLE CHAT WEBHOOK / EMAIL] Sending reminder to user {user.full_name} for trek {trek.name}")
                _send_email(
                    to=user.email,
                    subject=f"Jatayu | Your trek '{trek.name}' starts in {days_left} day(s)!",
                    body=f"Namaste {user.full_name}!\n\nYour trek '{trek.name}' begins on {trek.start_date.strftime('%B %d, %Y')}.\nLocation: {trek.location}\nDuration: {trek.duration_days} days\n\nPack well, trek safe.\n\n— Team Jatayu 🏔"
                )
                sent += 1
    return {"status": "done", "reminders_sent": sent}


def send_monthly_admin_report_non_celery():
    """Non-Celery monthly report."""
    from ..models import Trek, Booking, User
    total_treks = Trek.query.count()
    total_bookings = Booking.query.count()
    total_users = User.query.filter_by(role="trekker").count()
    completed = Booking.query.filter_by(status="Completed").count()

    popular = db.session.execute(
        db.text("""
            SELECT t.name, COUNT(b.id) as count
            FROM treks t
            JOIN bookings b ON t.id = b.trek_id
            GROUP BY t.id, t.name
            ORDER BY count DESC
            LIMIT 5
        """)
    ).fetchall()

    popular_html = "".join(
        f"<tr><td>{r[0]}</td><td>{r[1]}</td></tr>" for r in popular
    )

    html = f"""
    <html><body style="font-family:sans-serif;color:#1a1a1a">
    <h2 style="color:#0f2818">Jatayu — Monthly Report ({datetime.now().strftime('%B %Y')})</h2>
    <table border="0" cellpadding="8">
      <tr><td>Total Treks</td><td><b>{total_treks}</b></td></tr>
      <tr><td>Total Users</td><td><b>{total_users}</b></td></tr>
      <tr><td>Total Bookings</td><td><b>{total_bookings}</b></td></tr>
      <tr><td>Completed Bookings</td><td><b>{completed}</b></td></tr>
    </table>
    <h3>Most Popular Treks</h3>
    <table border="1" cellpadding="8" style="border-collapse:collapse">
      <tr><th>Trek</th><th>Bookings</th></tr>
      {popular_html}
    </table>
    <p style="color:#666;font-size:12px">Generated by Jatayu on {datetime.now().strftime('%d %B %Y')}</p>
    </body></html>
    """

    _send_email(
        to="admin@jatayu.in",
        subject=f"Jatayu Monthly Report — {datetime.now().strftime('%B %Y')}",
        body=html,
        is_html=True,
    )
    return {"status": "done", "month": datetime.now().strftime("%B %Y")}


@shared_task(bind=True)
def export_all_bookings_csv(self):
    """
    Admin-triggered async CSV export of all bookings.
    """
    from ..models import Booking
    bookings = Booking.query.order_by(Booking.created_at.desc()).all()

    output = io.StringIO()
    writer = csv.writer(output)
    writer.writerow([
        "Booking ID", "Trekker Name", "Trek Name", "Location",
        "Start Date", "End Date", "Booking Date",
        "Status", "Amount Paid", "Payment Method"
    ])

    for b in bookings:
        trek = b.trek
        trekker = b.user
        writer.writerow([
            b.id,
            trekker.full_name if trekker else "N/A",
            trek.name if trek else "N/A",
            trek.location if trek else "N/A",
            trek.start_date.isoformat() if trek and trek.start_date else "N/A",
            trek.end_date.isoformat() if trek and trek.end_date else "N/A",
            b.booking_date.strftime("%Y-%m-%d") if b.booking_date else "N/A",
            b.status,
            f"₹{b.amount_paid}" if b.amount_paid else "N/A",
            b.payment_method or "N/A",
        ])

    csv_content = output.getvalue()

    import os
    export_dir = "exports"
    os.makedirs(export_dir, exist_ok=True)
    filename = f"{export_dir}/all_bookings_export_{datetime.now().strftime('%Y%m%d%H%M%S')}.csv"
    with open(filename, "w", encoding="utf-8") as f:
        f.write(csv_content)

    # Send email notification to admin
    _send_email(
        to="admin@jatayu.in",
        subject="Jatayu | Admin Export of Bookings Ready",
        body=f"Namaste Admin! The CSV export of all bookings is ready and saved as {filename}."
    )

    return {"status": "done", "file": filename}

